/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 03 01:39:55 GMT 2016
 */
package com.descarteaqui.descarteaqui.model;
import com.descarteaqui.descarteaqui.model.Petition;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Petition_ESTest extends com.descarteaqui.descarteaqui.model.Petition_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Petition petition0 = new Petition(211, "", "", "", "");
      petition0.setRatesNG(211);
      petition0.unrateNG();
      assertEquals(210, petition0.getRatesNG());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Petition petition0 = new Petition((-1996), "", "JTg~@hb?&F;", ".M,pPnnV/~7}ct", "");
      petition0.setRatesNG((-1996));
      petition0.unrateNG();
      assertEquals(-1996, petition0.getRatesNG());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Petition petition0 = new Petition(0, "&v", "", "", "E4:{x:Mz[T/^0");
      petition0.setRatesOK((-781));
      petition0.rateOK();
      petition0.rateNG();
      assertEquals(-780, petition0.getRatesOK());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Petition petition0 = new Petition(0, "&v", "", "", "E4:{x:Mz[T/^0");
      String string0 = petition0.getStreetName();
      assertEquals("14/02/2014", petition0.getCreationDate());
      assertEquals("", petition0.getJustification());
      assertEquals(0, petition0.getRatesOK());
      assertEquals("&v", string0);
      assertEquals(0, petition0.getID());
      assertEquals("E4:{x:Mz[T/^0", petition0.getCreator());
      assertEquals(0, petition0.getRatesNG());
      assertEquals("", petition0.getDistrictName());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Petition petition0 = new Petition(0, "", "", "", "");
      petition0.getStreetName();
      assertEquals(0, petition0.getRatesNG());
      assertEquals(0, petition0.getID());
      assertEquals("14/02/2014", petition0.getCreationDate());
      assertEquals(0, petition0.getRatesOK());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Petition petition0 = new Petition(2282, (String) null, (String) null, "", "=R;6N^");
      petition0.setRatesOK(247);
      int int0 = petition0.getRatesOK();
      assertEquals(247, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Petition petition0 = new Petition(1726, "J", "J", "dd/MM/yyyy", "J");
      petition0.setRatesOK((-2167));
      int int0 = petition0.getRatesOK();
      assertEquals((-2167), int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Petition petition0 = new Petition(0, "", "", "", "");
      petition0.rateNG();
      int int0 = petition0.getRatesNG();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Petition petition0 = new Petition((-1), "(`k;|Ep-{6/", "(`k;|Ep-{6/", "", "");
      petition0.setRatesNG((-1));
      int int0 = petition0.getRatesNG();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Petition petition0 = new Petition((-2233), "Z:,7R", ":]>\"qZ", (String) null, "");
      String string0 = petition0.getJustification();
      assertEquals("", petition0.getCreator());
      assertEquals(0, petition0.getRatesNG());
      assertEquals("Z:,7R", petition0.getStreetName());
      assertNull(string0);
      assertEquals(":]>\"qZ", petition0.getDistrictName());
      assertEquals(-2233, petition0.getID());
      assertEquals("14/02/2014", petition0.getCreationDate());
      assertEquals(0, petition0.getRatesOK());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Petition petition0 = new Petition(0, "&v", "", "", "E4:{x:Mz[T/^0");
      String string0 = petition0.getJustification();
      assertEquals("E4:{x:Mz[T/^0", petition0.getCreator());
      assertEquals(0, petition0.getRatesNG());
      assertEquals(0, petition0.getRatesOK());
      assertEquals("", petition0.getDistrictName());
      assertEquals("14/02/2014", petition0.getCreationDate());
      assertEquals("", string0);
      assertEquals(0, petition0.getID());
      assertEquals("&v", petition0.getStreetName());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Petition petition0 = new Petition(0, "", "", "", "");
      int int0 = petition0.getID();
      assertEquals(0, int0);
      assertEquals(0, petition0.getRatesOK());
      assertEquals("14/02/2014", petition0.getCreationDate());
      assertEquals(0, petition0.getRatesNG());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Petition petition0 = new Petition(211, "", "", "", "");
      int int0 = petition0.getID();
      assertEquals(211, int0);
      assertEquals("14/02/2014", petition0.getCreationDate());
      assertEquals(0, petition0.getRatesOK());
      assertEquals(0, petition0.getRatesNG());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Petition petition0 = new Petition((-3859), "", "L/09y2!&(79A\"cR-JU", "", "");
      String string0 = petition0.getDistrictName();
      assertEquals(-3859, petition0.getID());
      assertEquals("", petition0.getStreetName());
      assertEquals("L/09y2!&(79A\"cR-JU", string0);
      assertEquals("", petition0.getJustification());
      assertEquals(0, petition0.getRatesOK());
      assertEquals("14/02/2014", petition0.getCreationDate());
      assertEquals("", petition0.getCreator());
      assertEquals(0, petition0.getRatesNG());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Petition petition0 = new Petition(0, "", "", "", "");
      petition0.getDistrictName();
      assertEquals(0, petition0.getRatesNG());
      assertEquals(0, petition0.getRatesOK());
      assertEquals("14/02/2014", petition0.getCreationDate());
      assertEquals(0, petition0.getID());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Petition petition0 = new Petition((-1996), "", "JTg~@hb?&F;", ".M,pPnnV/~7}ct", "");
      assertEquals("", petition0.getCreator());
      
      petition0.setCreator(".M,pPnnV/~7}ct");
      petition0.getCreator();
      assertEquals(-1996, petition0.getID());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Petition petition0 = new Petition(1, " ggJ(m8<faD%@NB{", "[=5?QoO,-sU)", " ggJ(m8<faD%@NB{", "");
      String string0 = petition0.getCreator();
      assertEquals(" ggJ(m8<faD%@NB{", petition0.getJustification());
      assertEquals(1, petition0.getID());
      assertEquals(0, petition0.getRatesNG());
      assertEquals("", string0);
      assertEquals("14/02/2014", petition0.getCreationDate());
      assertEquals("[=5?QoO,-sU)", petition0.getDistrictName());
      assertEquals(0, petition0.getRatesOK());
      assertEquals(" ggJ(m8<faD%@NB{", petition0.getStreetName());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Petition petition0 = new Petition(0, "", "", "", "");
      assertEquals("14/02/2014", petition0.getCreationDate());
      
      petition0.setCreationDate("");
      petition0.getCreationDate();
      assertEquals(0, petition0.getID());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Petition petition0 = new Petition(2282, (String) null, (String) null, "", "=R;6N^");
      petition0.unrateNG();
      assertEquals("=R;6N^", petition0.getCreator());
      assertEquals(0, petition0.getRatesOK());
      assertEquals(2282, petition0.getID());
      assertEquals(0, petition0.getRatesNG());
      assertEquals("14/02/2014", petition0.getCreationDate());
      assertEquals("", petition0.getJustification());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Petition petition0 = new Petition(2282, (String) null, (String) null, "", "=R;6N^");
      petition0.rateOK();
      petition0.rateNG();
      assertEquals(1, petition0.getRatesNG());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Petition petition0 = new Petition((-3859), "", "L/09y2!&(79A\"cR-JU", "", "");
      petition0.rateNG();
      petition0.rateNG();
      assertEquals(1, petition0.getRatesNG());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Petition petition0 = new Petition(1, " ggJ(m8<faD%@NB{", "[=5?QoO,-sU)", " ggJ(m8<faD%@NB{", "");
      petition0.unrateOK();
      assertEquals("14/02/2014", petition0.getCreationDate());
      assertEquals(" ggJ(m8<faD%@NB{", petition0.getStreetName());
      assertEquals(1, petition0.getID());
      assertEquals("[=5?QoO,-sU)", petition0.getDistrictName());
      assertEquals("", petition0.getCreator());
      assertEquals(0, petition0.getRatesNG());
      assertEquals(" ggJ(m8<faD%@NB{", petition0.getJustification());
      assertEquals(0, petition0.getRatesOK());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Petition petition0 = new Petition(2282, (String) null, (String) null, "", "=R;6N^");
      petition0.rateNG();
      petition0.rateOK();
      assertEquals(1, petition0.getRatesOK());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Petition petition0 = new Petition((-3859), "", "L/09y2!&(79A\"cR-JU", "", "");
      petition0.rateOK();
      petition0.rateOK();
      assertEquals(1, petition0.getRatesOK());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Petition petition0 = new Petition(2282, (String) null, (String) null, "", "=R;6N^");
      petition0.setDistrictName("");
      assertEquals(2282, petition0.getID());
      assertEquals(0, petition0.getRatesNG());
      assertEquals("14/02/2014", petition0.getCreationDate());
      assertEquals(0, petition0.getRatesOK());
      assertEquals("=R;6N^", petition0.getCreator());
      assertEquals("", petition0.getJustification());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Petition petition0 = new Petition(2282, (String) null, (String) null, "", "=R;6N^");
      assertEquals("", petition0.getJustification());
      
      petition0.setJustification("=R;6N^");
      assertEquals("14/02/2014", petition0.getCreationDate());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Petition petition0 = new Petition(2282, (String) null, (String) null, "", "=R;6N^");
      petition0.setStreetName("Q[m\"@M");
      assertEquals("", petition0.getJustification());
      assertEquals("14/02/2014", petition0.getCreationDate());
      assertEquals(0, petition0.getRatesOK());
      assertEquals(2282, petition0.getID());
      assertEquals("=R;6N^", petition0.getCreator());
      assertEquals(0, petition0.getRatesNG());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Petition petition0 = new Petition(2282, (String) null, (String) null, "", "=R;6N^");
      int int0 = petition0.getRatesOK();
      assertEquals(2282, petition0.getID());
      assertEquals(0, petition0.getRatesNG());
      assertEquals("=R;6N^", petition0.getCreator());
      assertEquals("", petition0.getJustification());
      assertEquals("14/02/2014", petition0.getCreationDate());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Petition petition0 = new Petition(2282, (String) null, (String) null, "", "=R;6N^");
      String string0 = petition0.getCreationDate();
      assertEquals("", petition0.getJustification());
      assertEquals(0, petition0.getRatesOK());
      assertEquals("=R;6N^", petition0.getCreator());
      assertEquals(2282, petition0.getID());
      assertEquals(0, petition0.getRatesNG());
      assertEquals("14/02/2014", string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Petition petition0 = new Petition((-1), "", "", " r8Y4:^.P6#74ry/EWq", " r8Y4:^.P6#74ry/EWq");
      String string0 = petition0.getJustification();
      assertEquals("14/02/2014", petition0.getCreationDate());
      assertEquals("", petition0.getStreetName());
      assertEquals(-1, petition0.getID());
      assertEquals(" r8Y4:^.P6#74ry/EWq", string0);
      assertEquals(" r8Y4:^.P6#74ry/EWq", petition0.getCreator());
      assertEquals(0, petition0.getRatesNG());
      assertEquals("", petition0.getDistrictName());
      assertEquals(0, petition0.getRatesOK());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Petition petition0 = new Petition(2282, (String) null, (String) null, "", "=R;6N^");
      String string0 = petition0.getStreetName();
      assertEquals("", petition0.getJustification());
      assertEquals(0, petition0.getRatesOK());
      assertEquals("=R;6N^", petition0.getCreator());
      assertEquals(2282, petition0.getID());
      assertEquals(0, petition0.getRatesNG());
      assertEquals("14/02/2014", petition0.getCreationDate());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Petition petition0 = new Petition(2282, (String) null, (String) null, "", "=R;6N^");
      assertEquals("14/02/2014", petition0.getCreationDate());
      
      petition0.setCreationDate((String) null);
      petition0.getCreationDate();
      assertEquals("", petition0.getJustification());
      assertEquals("=R;6N^", petition0.getCreator());
      assertEquals(0, petition0.getRatesOK());
      assertEquals(2282, petition0.getID());
      assertEquals(0, petition0.getRatesNG());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Petition petition0 = new Petition(2282, (String) null, (String) null, "", "=R;6N^");
      petition0.setRatesOK(247);
      petition0.unrateOK();
      assertEquals(246, petition0.getRatesOK());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Petition petition0 = new Petition(2282, (String) null, (String) null, "", "=R;6N^");
      int int0 = petition0.getRatesNG();
      assertEquals("14/02/2014", petition0.getCreationDate());
      assertEquals("", petition0.getJustification());
      assertEquals(0, petition0.getRatesOK());
      assertEquals(2282, petition0.getID());
      assertEquals("=R;6N^", petition0.getCreator());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Petition petition0 = new Petition((-236), "c,>8eR0f*A7e%|y~", (String) null, "c,>8eR0f*A7e%|y~", (String) null);
      String string0 = petition0.getCreator();
      assertEquals(0, petition0.getRatesNG());
      assertEquals(0, petition0.getRatesOK());
      assertEquals(-236, petition0.getID());
      assertEquals("14/02/2014", petition0.getCreationDate());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Petition petition0 = new Petition(1, (String) null, (String) null, (String) null, (String) null);
      petition0.getDistrictName();
      assertEquals("14/02/2014", petition0.getCreationDate());
      assertEquals(0, petition0.getRatesOK());
      assertEquals(0, petition0.getRatesNG());
      assertEquals(1, petition0.getID());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Petition petition0 = new Petition((-1996), "", "JTg~@hb?&F;", ".M,pPnnV/~7}ct", "");
      int int0 = petition0.getID();
      assertEquals("", petition0.getStreetName());
      assertEquals(0, petition0.getRatesOK());
      assertEquals("JTg~@hb?&F;", petition0.getDistrictName());
      assertEquals("14/02/2014", petition0.getCreationDate());
      assertEquals((-1996), int0);
      assertEquals(".M,pPnnV/~7}ct", petition0.getJustification());
      assertEquals("", petition0.getCreator());
      assertEquals(0, petition0.getRatesNG());
  }
}
